name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build Mac App
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: 'specter78/rclone-gui'
          token: ${{ secrets.PRIVATE_REPO_PAT }}
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Enable macOS Desktop Support
        run: flutter config --enable-macos-desktop
      - name: Create macOS Project Files
        run: flutter create --platforms=macos .
      - name: Build macOS Application
        run: flutter build macos --release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: macOS-Release-App
          path: build/macos/Build/Products/Release/
