name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build Mac App
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: 'specter78/rclone-gui'
          token: ${{ secrets.PRIVATE_REPO_PAT }}
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Enable macOS Desktop Support
        run: flutter config --enable-macos-desktop
      - name: Create macOS Project Files
        run: flutter create --platforms=macos .
      - name: Build macOS Application
        run: flutter build macos --release

      - name: Thin Binary to Apple Silicon (arm64) Only
        run: |
          cd build/macos/Build/Products/Release/rclone_gui.app/Contents
          lipo MacOS/rclone_gui -thin arm64 -output MacOS/rclone_gui
          lipo Frameworks/FlutterMacOS.framework/FlutterMacOS -thin arm64 -output Frameworks/FlutterMacOS.framework/FlutterMacOS
          lipo Frameworks/App.framework/App -thin arm64 -output Frameworks/App.framework/App

      - name: Package Application
        run: |
          cd build/macos/Build/Products/Release/
          zip -ry rclone_gui.zip rclone_gui.app

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: macOS-Release-App
          path: build/macos/Build/Products/Release/rclone_gui.zip
